version: '3'

services:

  queue:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-api
    environment:
      - AWS_SECRET_ACCESS_KEY=x
      - AWS_ACCESS_KEY_ID=x
    volumes:
      - .:/code
    ports:
      - "8080:8080"

  queue_creation:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-startqueue

  worker:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-worker
    volumes:
      - .:/code
    environment:
      - AWS_SECRET_ACCESS_KEY=x
      - AWS_ACCESS_KEY_ID=x
    depends_on:
      queue:
        condition: service_healthy
      queue_creation:
        condition: 'service_completed_successfully'

  queue2:
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
    healthcheck:
      test: wget -q -S -O - 127.0.0.1:9324/?Action=ListQueues
      interval: 10s
      timeout: 10s
      retries: 5