FROM python:3.10

COPY ./api/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

WORKDIR code

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8080"]
