FROM python:3.10

COPY ./api/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

WORKDIR code

CMD ["celery", "-A", "tasks.tasks", "worker", "-l", "INFO", "-c", "1"]